<?php


return [

    'app' => [
        'name'        => 'ADMISENA',
        'full_name'   => 'Servicio Nacional de Aprendizaje — SENA',
        'tagline'     => 'Formación técnica para transformar Colombia',
        'description' => 'Plataforma pública de información académica, programas de tecnología, noticias y eventos del SENA.',
    ],

    'contact' => [
        'address'    => 'Calle 57 No. 8 - 69, Bogotá D.C. — Colombia',
        'phone'      => '01 8000 910270',
        'whatsapp'   => '+57 320 000 0000',
        'email'      => 'contacto@admisena.edu.co',
        'schedule'   => 'Lunes a viernes, 8:00 a.m. – 5:30 p.m.',
    ],

    'locations' => [
        [
            'name'   => 'Centro de Comercio y Servicios',
            'slug'   => 'comercio-servicios',
            'accent' => '#7A2FBF',
            'blurb'  => 'Formación en servicios, gestión empresarial y tecnologías aplicadas al comercio.',
        ],
        [
            'name'   => 'Centro Agropecuario',
            'slug'   => 'agropecuario',
            'accent' => '#1769AA',
            'blurb'  => 'Programas del sector agropecuario y desarrollo rural en la región.',
        ],
        [
            'name'   => 'Ciudad Jardín',
            'slug'   => 'ciudad-jardin',
            'accent' => '#41BC03',
            'blurb'  => 'Oferta tecnológica y del sector salud con ambientes modernos de aprendizaje.',
        ],
    ],

    'programs' => [
        [
            'slug'       => 'analisis-desarrollo-software',
            'name'       => 'Análisis y Desarrollo de Software',
            'code'       => 'ADSO',
            'level'      => 'Tecnólogo',
            'duration'   => '27 meses',
            'modality'   => 'Presencial · Virtual',
            'accent'     => '#39A900',
            'image'      => 'images/software.jpg',
            'summary'    => 'Diseña, construye y despliega soluciones de software siguiendo estándares internacionales de calidad y metodologías ágiles.',
            'tags'       => ['programación', 'desarrollo web', 'bases de datos', 'ágil', 'código'],
        ],
        [
            'slug'       => 'gestion-redes-datos',
            'name'       => 'Gestión de Redes de Datos',
            'code'       => 'GRD',
            'level'      => 'Tecnólogo',
            'duration'   => '24 meses',
            'modality'   => 'Presencial',
            'accent'     => '#007832',
            'image'      => 'images/networks.jpg',
            'summary'    => 'Administra infraestructuras de red, configura equipos Cisco y garantiza la conectividad segura de las organizaciones.',
            'tags'       => ['redes', 'cisco', 'servidores', 'conectividad', 'routing'],
        ],
        [
            'slug'       => 'seguridad-informatica',
            'name'       => 'Seguridad Informática',
            'code'       => 'SI',
            'level'      => 'Tecnólogo',
            'duration'   => '24 meses',
            'modality'   => 'Presencial · Virtual',
            'accent'     => '#00324D',
            'image'      => 'images/security.jpg',
            'summary'    => 'Protege sistemas y datos: auditoría, criptografía, respuesta a incidentes y cumplimiento normativo digital.',
            'tags'       => ['ciberseguridad', 'hacking ético', 'criptografía', 'auditoría'],
        ],
        [
            'slug'       => 'gestion-agroempresarial',
            'name'       => 'Gestión Agroempresarial',
            'code'       => 'GAE',
            'level'      => 'Tecnólogo',
            'duration'   => '24 meses',
            'modality'   => 'Presencial',
            'accent'     => '#41BC03',
            'image'      => 'images/agro.jpg',
            'summary'    => 'Impulsa proyectos productivos del campo colombiano con innovación, sostenibilidad y visión empresarial.',
            'tags'       => ['agricultura', 'campo', 'sostenibilidad', 'proyectos productivos'],
        ],
        [
            'slug'       => 'electronica-industrial',
            'name'       => 'Mantenimiento Electrónico Industrial',
            'code'       => 'MEI',
            'level'      => 'Tecnólogo',
            'duration'   => '26 meses',
            'modality'   => 'Presencial',
            'accent'     => '#1769AA',
            'image'      => 'images/electronics.jpg',
            'summary'    => 'Opera y mantiene sistemas automatizados, PLC y control industrial en plantas de manufactura moderna.',
            'tags'       => ['automatización', 'PLC', 'control industrial', 'electrónica'],
        ],
        [
            'slug'       => 'gestion-logistica',
            'name'       => 'Gestión Logística',
            'code'       => 'GL',
            'level'      => 'Tecnólogo',
            'duration'   => '24 meses',
            'modality'   => 'Presencial · Virtual',
            'accent'     => '#E75A1C',
            'image'      => 'images/logistics.jpg',
            'summary'    => 'Optimiza cadenas de suministro, almacenes y transporte con herramientas de analítica y comercio exterior.',
            'tags'       => ['cadena de suministro', 'almacén', 'transporte', 'comercio exterior'],
        ],
        [
            'slug'       => 'multimedia',
            'name'       => 'Diseño e Integración de Multimedia',
            'code'       => 'DIM',
            'level'      => 'Tecnólogo',
            'duration'   => '25 meses',
            'modality'   => 'Presencial',
            'accent'     => '#7A2FBF',
            'image'      => 'images/multimedia.jpg',
            'summary'    => 'Crea experiencias digitales: animación, video, motion graphics y diseño interactivo para industrias creativas.',
            'tags'       => ['diseño', 'animación', 'video', 'motion graphics', 'UX'],
        ],
        [
            'slug'       => 'contabilidad-finanzas',
            'name'       => 'Contabilidad y Finanzas',
            'code'       => 'CF',
            'level'      => 'Tecnólogo',
            'duration'   => '24 meses',
            'modality'   => 'Presencial · Virtual',
            'accent'     => '#B58A00',
            'image'      => 'images/finance.jpg',
            'summary'    => 'Administra la información financiera de las organizaciones con NIIF, analítica de datos y control fiscal.',
            'tags'       => ['contabilidad', 'NIIF', 'finanzas', 'impuestos', 'nómina'],
        ],
    ],

    'news' => [
        [
            'slug'      => 'convocatoria-oferta-2026-2',
            'title'     => 'Abre la convocatoria de oferta regular 2026-II',
            'date'      => '2026-08-10',
            'category'  => 'Convocatorias',
            'excerpt'   => 'Más de 180 mil cupos en formación técnica, tecnológica y complementaria en los 33 centros de la región.',
            'body'      => [
                'El Servicio Nacional de Aprendizaje abrió la convocatoria de oferta regular para el segundo semestre de 2026, con más de 180 mil cupos distribuidos en formación técnica, tecnológica y complementaria.',
                'Los interesados podrán inscribirse a través de la plataforma oficial utilizando su documento de identidad. La oferta incluye los nuevos programas alineados con la cuarta revolución industrial: análisis de datos, ciberseguridad y automatización industrial.',
                'La fase de inscripción permanecerá abierta durante cuatro semanas. Se recomienda a los aspirantes verificar los requisitos del programa elegido y preparar sus documentos con anticipación.',
            ],
        ],
        [
            'slug'      => 'alianza-industria-4-0',
            'title'     => 'SENA firma alianza con gremio de industria 4.0',
            'date'      => '2026-07-28',
            'category'  => 'Alianzas',
            'excerpt'   => 'El convenio permitirá que aprendices realicen práctica productiva en fábricas inteligentes del país.',
            'body'      => [
                'Con la firma de este convenio, los aprendices de los programas tecnológicos tendrán acceso a práctica productiva en entornos reales de manufactura avanzada, robótica e internet industrial de las cosas.',
                'El acuerdo contempla además la actualización de laboratorios en ocho regionales y la certificación doble para los perfiles de mantenimiento electrónico y gestión de redes.',
                'Para el sector productivo, la alianza significa un canal directo de talento formado bajo estándares de industria 4.0, reduciendo costos de reclutamiento y capacitación.',
            ],
        ],
        [
            'slug'      => 'aprendices-medalla-worldskills',
            'title'     => 'Aprendices colombianos suben al podio en WorldSkills',
            'date'      => '2026-07-02',
            'category'  => 'Logros',
            'excerpt'   => 'Tres medallas en las áreas de mecatrónica, desarrollo web y cuidado estético en la competencia internacional.',
            'body'      => [
                'La delegación colombiana regresó con tres medallas de la competencia internacional WorldSkills, en las categorías de mecatrónica, desarrollo web y cuidado estético.',
                'Los tres medallistas son aprendices de tecnología del SENA que superaron a representantes de más de 60 países tras dos años de entrenamiento especializado.',
                'Este resultado consolida a Colombia entre los diez mejores países de América Latina en formación técnica y tecnológica.',
            ],
        ],
        [
            'slug'      => 'nuevos-laboratorios-regionales',
            'title'     => 'Inaugurados cinco laboratorios de innovación en regionales',
            'date'      => '2026-06-15',
            'category'  => 'Infraestructura',
            'excerpt'   => 'Espacios equipados con impresión 3D, realidad virtual y estaciones de desarrollo para uso de todos los programas.',
            'body'      => [
                'Cinco centros de formación estrenan laboratorios de innovación equipados con impresión 3D, realidad virtual, estaciones de desarrollo de software y equipos de prototipado rápido.',
                'Los espacios estarán disponibles para todos los programas de formación, promoviendo el trabajo interdisciplinario entre áreas tecnológicas.',
                'Cada laboratorio contará con instructores mediadores que acompañarán proyectos de emprendimiento y transferencia de conocimiento al sector productivo.',
            ],
        ],
        [
            'slug'      => 'bilinguismo-certificacion',
            'title'     => 'Nueva estrategia de bilingüismo certificará a 50 mil aprendices',
            'date'      => '2026-05-20',
            'category'  => 'Formación',
            'excerpt'   => 'El programa de inglés intensivo incluirá evaluación CEFR gratuita para aprendices de último nivel.',
            'body'      => [
                'La nueva estrategia de bilingüismo busca certificar el nivel de inglés de 50 mil aprendices bajo el marco común europeo CEFR, con evaluación gratuita para quienes cursen el último nivel de su programa.',
                'La formación se desarrollará en modalidad mixta: sesiones presenciales en centros bilingües y práctica autónoma en la plataforma virtual de idiomas.',
                'Los certificados de nivel B1 y B2 serán reconocidos por empresas aliadas y universidades con convenios de articulación.',
            ],
        ],
        [
            'slug'      => 'feria-emprendimiento-2026',
            'title'     => 'Feria de Emprendimiento reunirá a 800 unidades productivas',
            'date'      => '2026-04-30',
            'category'  => 'Eventos',
            'excerpt'   => 'Muestra nacional de empresas creadas por aprendices, con rueda de negocio y vitrina de innovación.',
            'body'      => [
                'La Feria Nacional de Emprendimiento exhibirá 800 unidades productivas creadas por aprendices de todas las regionales, desde agroindustria hasta desarrollo de software.',
                'El evento incluirá ruedas de negocio con compradores institucionales, mentorías de inversión y la final nacional del concurso de ideas empresariales.',
                'La entrada es libre y las unidades productivas participantes podrán acceder a convocatorias de capital semilla del sistema nacional de fomento.',
            ],
        ],
    ],

    'events' => [
        [
            'slug'   => 'jornada-inscripcion-abierta',
            'title'  => 'Jornada nacional de inscripción abierta',
            'date'   => '2026-09-05',
            'time'   => '8:00 a.m. – 4:00 p.m.',
            'place'  => 'Todos los centros de formación',
            'type'   => 'Admisiones',
            'detail' => 'Asesoría presencial para completar tu inscripción a programas técnicos y tecnológicos. Trae tu documento de identidad.',
        ],
        [
            'slug'   => 'hackathon-sena-datos',
            'title'  => 'Hackathon SENA Datos Abiertos',
            'date'   => '2026-09-18',
            'time'   => 'Viernes 5:00 p.m. – Domingo 6:00 p.m.',
            'place'  => 'Centro de Gestión Industrial — Bogotá',
            'type'   => 'Competencia',
            'detail' => '48 horas para construir soluciones con datos públicos. Equipos de hasta 4 integrantes, premios para las tres primeras soluciones.',
        ],
        [
            'slug'   => 'feria-tecnologica-regional',
            'title'  => 'Feria tecnológica regional',
            'date'   => '2026-10-08',
            'time'   => '9:00 a.m. – 5:00 p.m.',
            'place'  => 'Plaza mayor — Medellín',
            'type'   => 'Feria',
            'detail' => 'Exposición de proyectos finales de tecnólogos: automatización, software, multimedia y agroindustria. Entrada libre.',
        ],
        [
            'slug'   => 'ceremonia-graduacion-titulados',
            'title'  => 'Ceremonia de graduación de titulados',
            'date'   => '2026-11-12',
            'time'   => '2:00 p.m.',
            'place'  => 'Centro de convenciones — Cali',
            'type'   => 'Ceremonia',
            'detail' => 'Encuentro de titulados del segundo semestre. Inscripción previa obligatoria para graduandos y acompañantes.',
        ],
        [
            'slug'   => 'charla-ciberseguridad-mujeres',
            'title'  => 'Charla: mujeres que lideran la ciberseguridad',
            'date'   => '2026-09-25',
            'time'   => '10:00 a.m.',
            'place'  => 'Auditorio virtual (transmisión en vivo)',
            'type'   => 'Charla',
            'detail' => 'Panel con expertas del sector financiero y de gobierno sobre rutas de carrera en ciberseguridad. Con traducción a lenguaje de señas.',
        ],
    ],

    'faqs' => [
        [
            'q' => '¿Cómo me inscribo a un programa?',
            'a' => 'Ingresa a la plataforma de admisiones con tu documento de identidad, selecciona el programa y el centro de formación, y completa tus datos personales. Recibirás la citación a selección por correo electrónico.',
        ],
        [
            'q' => '¿Cuáles son los requisitos de edad?',
            'a' => 'Para formación técnica y tecnológica se requiere tener al menos 14 años (formación técnica) o 16 años (tecnológica) y haber culminado mínimo grado décimo; para tecnólogos se requiere bachiller académico.',
        ],
        [
            'q' => '¿La formación tiene costo?',
            'a' => 'No. Toda la formación titulada del SENA es completamente gratuita para los colombianos, incluyendo materiales de formación en los ambientes de aprendizaje.',
        ],
        [
            'q' => '¿Puedo estudiar virtualmente?',
            'a' => 'Sí. Varios programas tecnológicos ofrecen modalidad virtual o presencial-virtual. Consulta la ficha de cada programa para conocer la modalidad disponible.',
        ],
        [
            'q' => '¿Qué es una ficha?',
            'a' => 'La ficha es el grupo de aprendizaje con el que ingresas: identifica tu programa, jornada, centro de formación y compañeros durante toda la ruta formativa.',
        ],
    ],
];
